<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Ad67Ym\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Ad67Ym/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0Ad67Ym.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0Ad67Ym\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container0Ad67Ym\srcDevDebugProjectContainer(array(
    'container.build_hash' => '0Ad67Ym',
    'container.build_id' => 'de884acf',
    'container.build_time' => 1536892837,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0Ad67Ym');
